server:
  port: 8084
spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 172.16.6.124:8848,172.16.5.16:8848,172.16.5.17:8848
        namespace: public
dubbo:
  registry:
    address: spring-cloud://localhost
  provider:
    dynamic: true
    timeout: 10000
  consumer:
    check: false
    timeout: 10000
logging:
  config: classpath:logback-spring.xml
feign:
  hystrix:
    enabled: true